### ISSUE TITLE
Reinvent shellder with a proper programming language.

### ISSUE THREAD

**Issue by simnalamburt** [simnalamburt/shellder#10]
#### Why?

I want to use shellder in everywhere (sh, bash, zsh, fish) and reinventing shellder in each shell language is a mad journey. By reinventing shellder in a proper programming language and distributing it as executable binary, I can achieve three goals at once.
1.  Performance
   
   Most programming language is faster than shell script.
2.  Cross platform.
   
   Compiled binary doesn't discriminate shells. When it is executed in `$PS1`, it will just work fine.
3.  Easy Development
   
   Shell scripts are crazy and there're full of unexpected behaviors. You just shouldn't develop something in shell script unless [you're writing tiny utility](https://google.github.io/styleguide/shell.xml?showone=When_to_use_Shell#When_to_use_Shell). And now I see shellder as more than just small utility or wrapper.
#### So, which PL are you going to use?

Requirements
- Speed
- It should be able to compiled in binary, and executed without any dependency.
- Easier than shell script.
- It should support Windows (cygwin, msys2), OS X and Linux. Both 32 and 64bit. Deployment will be (hopefully) automated with CI tools like travis.

Candidates
- [Go](https://golang.org/) (easy > speed)
- [Rust](https://www.rust-lang.org/) (easy < speed)

Related with #9
Closes #5

**Comment by bucaran** [comment]
I agree with performance and the cross-platform issue, but I think developing in a shell script is easier to develop. We could start arguing about this and saying the pros and cons, etc. But here is one proof, you wrote shellder in a shell script language. Why? Because it was easy and faster to prototype.

Even if you are a mad scientist in Go or Rust, not everyone is. 

Now, I really hope you write Shellder in a "real" programming language as that's my new favorite theme :smile:

**Comment by andrewrynhard** [comment]
I would be willing to lend a hand. I have a bit of experience with rust.  I have even more with go but I am always in favor of speed and rusts memory check system is excellent!

**Comment by kalbasit** [comment]
I can also help you out if you choose to use Go.

**Comment by simnalamburt** [comment]
https://starship.rs/ Did this. Closing
